apiVersion: zookeeper.stackable.tech/v1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.4.14
  config:
    port: 1111
  config_overrides:
    port: 2222
  servers:
    config:
      port: 1111
    config_overrides:
      port: 2222
    role_groups:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: main-1.stackable.demo
        replicas: 1
        config:
          port: 1111
          ticktime: 2
          syncLimit: 5
          metaXY: true
        config_overrides:
          port: 2222

