apiVersion: zookeeper.stackable.tech/v1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/arch: stackable-linux
        instances: 1
        instancesPerNode: 1
