# SPDX-FileCopyrightText: 2021 Stackable GmbH <info@stackable.de>
#
# SPDX-License-Identifier: OSL-3.0

name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
